# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ScrapperUI.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import pandas as pd
from yahoo_fin.stock_info import get_data

class Ui_MainWindow(QtWidgets.QWidget):
    def setupUi(self, MainWindow):
        ################# Window Configuration #################
        MainWindow.setObjectName("MainWindow")
        MainWindow.setEnabled(True)
        MainWindow.resize(650, 500)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMinimumSize(QtCore.QSize(650, 500))
        MainWindow.setMaximumSize(QtCore.QSize(650, 500))
        font = QtGui.QFont()
        font.setFamily("Georgia")
        font.setBold(True)
        font.setWeight(75)
        MainWindow.setFont(font)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")

        ############## UI Elements Configuration ###############
        # Title Text
        self.titleTxt = QtWidgets.QLabel(self.centralwidget)
        self.titleTxt.setGeometry(QtCore.QRect(10, 0, 221, 31))
        font = QtGui.QFont()
        font.setFamily("Georgia")
        font.setBold(True)
        font.setWeight(75)
        self.titleTxt.setFont(font)
        self.titleTxt.setAutoFillBackground(True)
        self.titleTxt.setScaledContents(True)
        self.titleTxt.setIndent(-1)
        self.titleTxt.setObjectName("titleTxt")

        # Ticker Text
        self.tickerTxt = QtWidgets.QLabel(self.centralwidget)
        self.tickerTxt.setGeometry(QtCore.QRect(40, 40, 91, 21))
        font = QtGui.QFont()
        font.setFamily("Georgia")
        font.setBold(False)
        font.setWeight(50)
        self.tickerTxt.setFont(font)
        self.tickerTxt.setTextFormat(QtCore.Qt.PlainText)
        self.tickerTxt.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.tickerTxt.setIndent(0)
        self.tickerTxt.setObjectName("tickerTxt")

        # Ticker TextBox
        self.tickerTxtbox = QtWidgets.QTextEdit(self.centralwidget)
        self.tickerTxtbox.setGeometry(QtCore.QRect(130, 40, 104, 21))
        self.tickerTxtbox.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.tickerTxtbox.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        font = QtGui.QFont()
        font.setCapitalization(1)
        font.setWeight(50)
        self.tickerTxtbox.setFont(font)
        self.tickerTxtbox.setLineWrapMode(QtWidgets.QTextEdit.FixedPixelWidth)
        self.tickerTxtbox.setLineWrapColumnOrWidth(-1)
        self.tickerTxtbox.setReadOnly(False)
        self.tickerTxtbox.setObjectName("tickerTxtbox")
        self.tickerTxtbox.textChanged.connect(self.ticker_TextChanged)
        self.tickerTxtbox.installEventFilter(self) #Filter Enter/Return key press event with using textbox

        # Insert Button
        self.insertBtn = QtWidgets.QPushButton(self.centralwidget)
        self.insertBtn.setGeometry(QtCore.QRect(240, 40, 61, 20))
        self.insertBtn.setObjectName("insertBtn")
        self.insertBtn.clicked.connect(self.insertBtn_clicked)

        # Ticker List
        self.tickerListView = QtWidgets.QListWidget(self.centralwidget)
        self.tickerListView.setGeometry(QtCore.QRect(330, 30, 301, 171))

        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tickerListView.sizePolicy().hasHeightForWidth())
        self.tickerListView.setSizePolicy(sizePolicy)
        
        self.tickerListView.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.tickerListView.setObjectName("tickerListView")

        # Ticker Count Text
        self.tickerCountTxt = QtWidgets.QLabel(self.centralwidget)
        self.tickerCountTxt.setGeometry(QtCore.QRect(330, 210, 120, 21))
        self.tickerCountTxt.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.tickerCountTxt.setWordWrap(True)
        self.tickerCountTxt.setObjectName("tickerCountTxt")

        # Submit Button
        self.submitBtn = QtWidgets.QPushButton(self.centralwidget)
        self.submitBtn.setGeometry(QtCore.QRect(530, 210, 101, 23))
        self.submitBtn.setObjectName("submitBtn")

        # Line Seperator
        self.line = QtWidgets.QFrame(self.centralwidget)
        self.line.setGeometry(QtCore.QRect(0, 230, 651, 16))
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")       

        # Dataframe Table
        self.dfList = QtWidgets.QTableView(self.centralwidget)
        self.dfList.setGeometry(QtCore.QRect(10, 250, 631, 211))
        self.dfList.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.dfList.setObjectName("dfList")

        # Export Button
        self.exportBtn = QtWidgets.QPushButton(self.centralwidget)
        self.exportBtn.setGeometry(QtCore.QRect(560, 470, 81, 23))
        self.exportBtn.setObjectName("exportBtn")
        
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        #self.tickerListView.setCurrentRow(-1)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)


    ################## Text Configuration ##################
    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Peaky Buyer"))
        self.titleTxt.setText(_translate("MainWindow", "Fundamental Analysis Extracter"))
        self.tickerTxt.setText(_translate("MainWindow", "Ticker Symbol: "))
        self.insertBtn.setText(_translate("MainWindow", "Insert"))
        self.exportBtn.setText(_translate("MainWindow", "Export"))
        self.submitBtn.setText(_translate("MainWindow", "Submit"))

        # Count no. of stocks added to list
        tickerCount = self.tickerListView.count()
        self.tickerCountTxt.setText(_translate("MainWindow", "No. of Stocks: " + str(tickerCount)))


    ################# UI Element  #################
    def ticker_TextChanged(self):
        # Limit Ticker Symbol length to 5
        if len(self.tickerTxtbox.toPlainText()) > 5:
            symbol = self.tickerTxtbox.toPlainText()
            self.tickerTxtbox.setPlainText(symbol[0:5])
            self.tickerTxtbox.moveCursor(QtGui.QTextCursor.End)


    def insertBtn_clicked(self):
        ticker = self.tickerTxtbox.toPlainText().upper()

        if (isBlank(ticker) == False):        
            # Adjusting Item Height
            # item = QtWidgets.QListWidgetItem(ticker)
            # item.setSizeHint(QtCore.QSize(self.tickerListView.width(),15))
            self.tickerListView.addItem(ticker)
            self.updateTickerCount()

        self.tickerTxtbox.clear()


    def updateTickerCount(self):
        # Count no. of stocks in list
        tickerCount = self.tickerListView.count()
        self.tickerCountTxt.setText("No. of Stocks: " + str(tickerCount)) 


    def submitTickerList(self):
        # Retrieve and store all ticker in list
        stocks = []
        for i in range(self.tickerListView.count() - 1):
            stocks.append(self.tickerListView.item(i))
        
        df_finance = getFinanceData(stocks)

        
    
    ############### Event Handler  ################
    def eventFilter(self, obj, e):
        # Keypress Event
        if e.type() == QtCore.QEvent.Type(6) and obj is self.tickerTxtbox:
            if e.key() in (QtCore.Qt.Key_Return, QtCore.Qt.Key_Enter):
                self.insertBtn_clicked()
        return super().eventFilter(obj, e)





# String Is Blank
def isBlank(string):
    return (string and string.isspace())


# Retrieving Financial Data via Yahoo Finance API
#def getFinanceData(stockList):
    # Informations to obtain
    # P/E Ratio
    # P/BV Ratio
    # Debt/Equity Ration
    # Operating Profit Margin
    # EV/EBITDA
    # Price/Earning Growth Ratio
    # Interest Coverage Ratio
    # Current Ratio
    # Asset Turnover Ratio
    # Dividend Yield










if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
