# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ScrapperUI.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import pandas as pd

class TextEdit(QtWidgets.QTextEdit):
    def keyPressEvent(self, e):
        # Over multi-line inputs for QTextEdit
        if e.key() in (QtCore.Qt.Key_Return, QtCore.Qt.Key_Enter):
            return
        super().keyPressEvent(e)


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        ################# Window Configuration #################
        MainWindow.setObjectName("MainWindow")
        MainWindow.setEnabled(True)
        MainWindow.resize(650, 500)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMinimumSize(QtCore.QSize(650, 500))
        MainWindow.setMaximumSize(QtCore.QSize(650, 500))
        font = QtGui.QFont()
        font.setFamily("Georgia")
        font.setBold(True)
        font.setWeight(75)
        MainWindow.setFont(font)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")

        ############## UI Elements Configuration ###############
        # Title Text
        self.titleTxt = QtWidgets.QLabel(self.centralwidget)
        self.titleTxt.setGeometry(QtCore.QRect(10, 0, 221, 31))
        font = QtGui.QFont()
        font.setFamily("Georgia")
        font.setBold(True)
        font.setWeight(75)
        self.titleTxt.setFont(font)
        self.titleTxt.setAutoFillBackground(True)
        self.titleTxt.setWordWrap(True)
        self.titleTxt.setIndent(-1)
        self.titleTxt.setObjectName("titleTxt")

        # Ticker Text
        self.tickerTxt = QtWidgets.QLabel(self.centralwidget)
        self.tickerTxt.setGeometry(QtCore.QRect(40, 40, 91, 21))
        font = QtGui.QFont()
        font.setFamily("Georgia")
        font.setBold(False)
        font.setWeight(50)
        self.tickerTxt.setFont(font)
        self.tickerTxt.setTextFormat(QtCore.Qt.PlainText)
        self.tickerTxt.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.tickerTxt.setIndent(0)
        self.tickerTxt.setObjectName("tickerTxt")

        # Ticker TextBox
        self.tickerTxtbox = TextEdit(self.centralwidget)
        self.tickerTxtbox.setGeometry(QtCore.QRect(130, 40, 104, 21))
        self.tickerTxtbox.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.tickerTxtbox.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        font = QtGui.QFont()
        font.setCapitalization(1)
        font.setWeight(50)
        self.tickerTxtbox.setFont(font)
        self.tickerTxtbox.setLineWrapMode(QtWidgets.QTextEdit.FixedPixelWidth)
        self.tickerTxtbox.setLineWrapColumnOrWidth(-1)
        self.tickerTxtbox.setReadOnly(False)
        self.tickerTxtbox.setObjectName("tickerTxtbox")
        self.tickerTxtbox.textChanged.connect(self.ticker_TextChanged)
        # Enter/Return key press event with using textbox
        # self.tickerTxtbox.keyPressEvent = self.inputKeyPressEvent #Currently restricts all other input


        # Insert Button
        self.insertBtn = QtWidgets.QPushButton(self.centralwidget)
        self.insertBtn.setGeometry(QtCore.QRect(240, 40, 61, 20))
        self.insertBtn.setObjectName("insertBtn")
        self.insertBtn.clicked.connect(self.insertBtn_clicked)

        # Ticker List
        self.tickerList = QtWidgets.QListWidget(self.centralwidget)
        self.tickerList.setGeometry(QtCore.QRect(330, 30, 301, 171))
        self.tickerList.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.tickerList.setObjectName("tickerList")

        # Ticker Count Text
        self.tickerCountTxt = QtWidgets.QLabel(self.centralwidget)
        self.tickerCountTxt.setGeometry(QtCore.QRect(330, 210, 111, 21))
        self.tickerCountTxt.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.tickerCountTxt.setWordWrap(True)
        self.tickerCountTxt.setObjectName("tickerCountTxt")

        # Submit Button
        self.submitBtn = QtWidgets.QPushButton(self.centralwidget)
        self.submitBtn.setGeometry(QtCore.QRect(530, 210, 101, 23))
        self.submitBtn.setObjectName("submitBtn")

        # Line Seperator
        self.line = QtWidgets.QFrame(self.centralwidget)
        self.line.setGeometry(QtCore.QRect(0, 230, 651, 16))
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")       

        # Dataframe Table
        self.dfList = QtWidgets.QTableView(self.centralwidget)
        self.dfList.setGeometry(QtCore.QRect(10, 250, 631, 211))
        self.dfList.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.dfList.setObjectName("dfList")

        # Export Button
        self.exportBtn = QtWidgets.QPushButton(self.centralwidget)
        self.exportBtn.setGeometry(QtCore.QRect(560, 470, 81, 23))
        self.exportBtn.setObjectName("exportBtn")

        
        
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.tickerList.setCurrentRow(-1)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    ################## Text Configuration ##################
    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Peaky Buyer"))
        self.titleTxt.setText(_translate("MainWindow", "Fundamental Analysis Extracter"))
        self.tickerTxt.setText(_translate("MainWindow", "Ticker Symbol:"))
        self.insertBtn.setText(_translate("MainWindow", "Insert"))
        self.exportBtn.setText(_translate("MainWindow", "Export"))
        self.submitBtn.setText(_translate("MainWindow", "Submit"))

        # Count no. of stocks added to list
        tickerCount = self.tickerList.count()
        self.tickerCountTxt.setText(_translate("MainWindow", "No. of Stocks: " + str(tickerCount)))

    ################# UI Element  #################
    def ticker_TextChanged(self):
        # Limit Ticker Symbol length to 5
        if len(self.tickerTxtbox.toPlainText()) > 5:
            symbol = self.tickerTxtbox.toPlainText()
            self.tickerTxtbox.setPlainText(symbol[0:5])
            self.tickerTxtbox.moveCursor(QtGui.QTextCursor.End)


    def insertBtn_clicked(self):
        ticker = self.tickerTxtbox.toPlainText().upper()
        self.tickerTxtbox.clear()
        self.tickerList.addItem(ticker)

        # Count no. of stocks added to list
        tickerCount = self.tickerList.count()
        self.tickerCountTxt.setText("No. of Stocks: " + str(tickerCount))

    
    ############### Key Press Event  ###############
    # def inputKeyPressEvent(self, e):
    #     if e.key() in (QtCore.Qt.Key_Return, QtCore.Qt.Key_Enter):
    #         self.insertBtn_clicked()



if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
